// Scan QR generated by index.html (payload JSON stored by data.js)
// Marks enrollment as "checked" in localStorage and prevents duplicates.

function setStatus(message, type = "") {
  const status = document.getElementById("status");
  status.textContent = message || "";
  status.classList.remove("ok", "warn", "err");
  if (type) status.classList.add(type);
}

function handleDecodedText(decodedText) {
  let payload;
  try {
    payload = JSON.parse(decodedText);
  } catch {
    setStatus("This QR is not from this generator (invalid JSON).", "err");
    return;
  }

  const name = String(payload?.name || "").trim();
  const enrollment = String(payload?.enrollment || "").trim().toUpperCase();
  const timestamp = Number(payload?.issuedAt || payload?.timestamp || 0);
  const token = String(payload?.token || "");

  if (!name || !enrollment) {
    setStatus("QR JSON missing name/enrollment.", "err");
    return;
  }

  if (!window.QRData) {
    setStatus("Data module not loaded.", "err");
    return;
  }

  // Verify it was actually generated (one-time generation)
  const generated = window.QRData.getGenerated();
  const gen = generated[enrollment];
  if (!gen || gen.token !== token) {
    setStatus("Invalid QR (not generated by this system).", "err");
    return;
  }

  const checked = window.QRData.getChecked();
  const existing = checked[enrollment];
  if (existing) {
    setStatus("Student already scanned", "warn");
    return;
  }

  checked[enrollment] = {
    name,
    enrollment,
    timestamp,
    checkedAt: Date.now(),
  };
  window.QRData.saveChecked(checked);

  setStatus(`Checked ✓ ${name} (${enrollment})`, "ok");
}

document.addEventListener("DOMContentLoaded", () => {
  // Gate scanner page behind password
  // NOTE: relies entirely on auth.js now. Previously there was a second,
  // separate hardcoded password here that could silently go stale if the
  // real one in auth.js was ever changed.
  if (!window.AppAuth) {
    alert("Auth module (auth.js) failed to load. Cannot verify scanner access.");
    window.location.href = "./index.html";
    return;
  }
  if (!window.AppAuth.requireScannerOrRedirect()) return;

  const startBtn = document.getElementById("startBtn");
  const stopBtn = document.getElementById("stopBtn");

  const html5QrCode = typeof Html5Qrcode === "function" ? new Html5Qrcode("reader") : null;
  let isScanning = false;

  if (!html5QrCode) {
    setStatus("Scanner library failed to load.", "err");
    startBtn.disabled = true;
    stopBtn.disabled = true;
    return;
  }

  async function startScan() {
    if (isScanning) return;
    isScanning = true;
    startBtn.disabled = true;
    stopBtn.disabled = false;

    setStatus("Scanning... hold QR steady.", "");
    try {
      await html5QrCode.start(
        { facingMode: "environment" },
        { fps: 10, qrbox: { width: 270, height: 270 } },
        async (decodedText) => {
          // stop after first successful scan to avoid duplicate marking
          await stopScan();
          handleDecodedText(decodedText);
        },
        () => {}
      );
    } catch (e) {
      isScanning = false;
      startBtn.disabled = false;
      stopBtn.disabled = true;
      setStatus("Camera access denied or unavailable.", "err");
      console.error(e);
    }
  }

  async function stopScan() {
    if (!isScanning) return;
    try {
      await html5QrCode.stop();
      await html5QrCode.clear();
    } catch {
      // ignore
    } finally {
      isScanning = false;
      startBtn.disabled = false;
      stopBtn.disabled = true;
    }
  }

  startBtn.addEventListener("click", startScan);
  stopBtn.addEventListener("click", stopScan);
});
